version: 2
updates:
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      types:
        patterns:
          - '@types/*'
      mantine:
        patterns:
          - '@mantine/*'
      three:
        patterns:
          - 'three'
          - '@types/three'
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
